site_name: TheStrechh

markdown_extensions:
  - toc:
      permalink: true

theme:
  name: material
  font:
    text: Ysabeau Office

  features:
    - navigation.tabs

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: blue

nav:
    - Getting started: 'index.md'
    - Download links: 'downloads.md'
    - Troubleshooting: 'troubleshooting.md'
