site_name: Carlos Arriaga
repo_url: https://github.com/TheStrechh/TheStrechh.github.io
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true

theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
  font:
    text: Ysabeau Office

  features:
    - navigation.tabs
    - navigation.footer

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: blue

nav:
    - Getting started: 'index.md'
    - Download links: 'downloads.md'
    - Troubleshooting: 'troubleshooting.md'

copyright: Copyright &copy; 2022 - 2023 Carlos Arriaga
