# Project information
site_name: Carlos Arriaga
site_url: https://github.com/ItsTheStrechh/ItsTheStrechh.github.io
site_author: Carlos Arriaga (TheStrechh)

# Repository
repo_name: TheStrechh/TheStrechh.github.io
repo_url: https://github.com/TheStrechh/TheStrechh.github.io

# Extensions
markdown_extensions:
  - toc:
      permalink: true

# Configuration
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
  font:
    text: Ysabeau Office

  features:
    - navigation.tabs
    - navigation.footer

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: blue

nav:
  - Getting started: 'index.md'
  - Download links: 'downloads.md'
  - Troubleshooting: 'troubleshooting.md'

# Copyright
copyright: Copyright &copy; 2022 - 2023 Carlos Arriaga
